version: '3.8'
services:
  binance:
    restart: always
    build:
      context: .
      dockerfile: ./apps/binance/Dockerfile
    environment:
      - REDIS_URI=redis://host.docker.internal:6379
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_USERNAME=postgres
      - DB_PASSWORD=ZXsPxuFQJzK1LAmA
      - DB_NAME=postgres
      - SYMBOLS=${SYMBOLS}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    entrypoint: ['node', 'dist/main.js']
    ports:
      - 5000:3000
  bybit:
    restart: always
    build:
      context: .
      dockerfile: ./apps/bybit/Dockerfile
    environment:
      - REDIS_URI=redis://host.docker.internal:6379
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_USERNAME=postgres
      - DB_PASSWORD=ZXsPxuFQJzK1LAmA
      - DB_NAME=postgres
      - SYMBOLS=${SYMBOLS}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    entrypoint: ['node', 'dist/main.js']
    ports:
      - 5001:3000
