version: '3.8'
services:
  binance:
    restart: always
    build:
      context: .
      dockerfile: ./apps/binance/Dockerfile
    environment:
      - DB_URL=${DB_URL}
      - SYMBOLS=${SYMBOLS}
      - USE_RABBITMQ=${USE_RABBITMQ}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    entrypoint: ['node', 'dist/main.js']
    ports:
      - 5000:3000
  bybit:
    restart: always
    build:
      context: .
      dockerfile: ./apps/bybit/Dockerfile
    environment:
      - DB_URL=${DB_URL}
      - SYMBOLS=${SYMBOLS}
      - USE_RABBITMQ=${USE_RABBITMQ}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    entrypoint: ['node', 'dist/main.js']
    ports:
      - 5001:3000
